// Địa chỉ file: app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { CartProvider } from "@/app/component/cart"; 
import { AuthProvider } from "@/app/component/AuthContext"; // Import Provider
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Chatbot from "./component/Chatbot";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Thực phẩm thiên nhiên",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-gray-900`}>
        
        {/* BẮT BUỘC: Bọc AuthProvider ngoài cùng */}
        <AuthProvider>
            
            <CartProvider>
              
              <ToastContainer position="top-right" autoClose={3000} />
              
              {/* Children (PublicLayout hoặc AdminLayout) */}
              {children}

            </CartProvider>

        </AuthProvider>
<Chatbot />
      </body>
    </html>
  );
}